/**
 * Copies the kiosk's own Hindi wording into the backend, so the Hindi history summary says a complaint in
 * exactly the words the patient tapped on the kiosk (no second translation to keep in step, and no model).
 *
 *   npx tsx scripts/sync-kiosk-labels.ts           write src/data/kiosk_labels_hi.json
 *   npx tsx scripts/sync-kiosk-labels.ts --check   exit 1 when the copy is stale (used by the tests)
 *
 * Source of truth: frontend/src/utils/kioskSymptomCatalog.ts and kioskLocalization.ts.
 */
import fs from 'fs';
import path from 'path';
import { PRIVATE_SYMPTOMS, REGIONAL_SYMPTOMS, REGION_TO_CATEGORY, SYSTEMIC_SYMPTOMS } from '../../frontend/src/utils/kioskSymptomCatalog';
import { PAIN_CHARACTERS, kioskText, regionName } from '../../frontend/src/utils/kioskLocalization';

const OUT = path.resolve(__dirname, '../src/data/kiosk_labels_hi.json');

export function buildKioskLabels() {
  const tx = kioskText('hi');
  const sorted = (o: Record<string, string>) => Object.fromEntries(Object.entries(o).sort(([a], [b]) => a.localeCompare(b)));

  const symptoms: Record<string, string> = {};
  for (const s of [...Object.values(REGIONAL_SYMPTOMS).flat(), ...Object.values(SYSTEMIC_SYMPTOMS).flat(), ...PRIVATE_SYMPTOMS]) {
    if (s.en && s.hi) symptoms[s.en] = s.hi;
  }

  // every body area the kiosk can store as a complaint's site, including the right-hand twin of each left one
  const regions: Record<string, string> = {};
  const ids = new Set([...Object.keys(REGIONAL_SYMPTOMS), ...Object.keys(REGION_TO_CATEGORY)]);
  for (const id of [...ids]) if (/^Left /.test(id)) ids.add(id.replace(/^Left /, 'Right '));
  for (const id of ids) {
    const hi = regionName(id, 'hi');
    if (hi && hi !== id) regions[id] = hi;
  }

  const characters: Record<string, string> = {};
  for (const c of PAIN_CHARACTERS) characters[c.value] = tx(c.key);

  const durations: Record<string, string> = {
    'Since today': tx('durToday'), '2–3 days': tx('dur23'), 'About a week': tx('durWeek'), '1 month or more': tx('durMonth')
  };

  return {
    note: 'GENERATED by backend/scripts/sync-kiosk-labels.ts from the kiosk catalog in frontend/src/utils — do not edit here.',
    symptoms: sorted(symptoms), regions: sorted(regions), characters: sorted(characters), durations
  };
}

if (require.main === module) {
  const want = JSON.stringify(buildKioskLabels(), null, 2) + '\n';
  if (process.argv.includes('--check')) {
    const ok = fs.existsSync(OUT) && fs.readFileSync(OUT, 'utf8') === want;
    console.log(ok ? 'kiosk_labels_hi.json is in sync' : 'backend/src/data/kiosk_labels_hi.json is stale — run npx tsx scripts/sync-kiosk-labels.ts');
    process.exit(ok ? 0 : 1);
  }
  fs.writeFileSync(OUT, want);
  const l = buildKioskLabels();
  console.log(`wrote ${OUT}: ${Object.keys(l.symptoms).length} symptoms, ${Object.keys(l.regions).length} body areas, ${Object.keys(l.characters).length} characters, ${Object.keys(l.durations).length} durations`);
}
