/**
 * Usual adult starting regimens for common OPD medicines, offered as an editable default when the
 * doctor picks a medicine (speed), never applied silently. Frequencies use Indian 1-0-1 notation.
 * Source: national standard treatment guidance / product labels; the hospital DTC may edit.
 */
export const COMMON_DOSES: Record<string, { dosage: string; frequency: string; durationDays: number; food?: string }> = {
  paracetamol: { dosage: '650 mg', frequency: '1-1-1', durationDays: 3, food: 'after food' },
  ibuprofen: { dosage: '400 mg', frequency: '1-0-1', durationDays: 3, food: 'after food' },
  diclofenac: { dosage: '50 mg', frequency: '1-0-1', durationDays: 3, food: 'after food' },
  aceclofenac: { dosage: '100 mg', frequency: '1-0-1', durationDays: 3, food: 'after food' },
  amoxicillin: { dosage: '500 mg', frequency: '1-1-1', durationDays: 5 },
  amoxicillin_clavulanate: { dosage: '625 mg', frequency: '1-0-1', durationDays: 5, food: 'after food' },
  azithromycin: { dosage: '500 mg', frequency: '1-0-0', durationDays: 3 },
  cefixime: { dosage: '200 mg', frequency: '1-0-1', durationDays: 5 },
  cephalexin: { dosage: '500 mg', frequency: '1-1-1', durationDays: 5 },
  doxycycline: { dosage: '100 mg', frequency: '1-0-1', durationDays: 7, food: 'after food' },
  nitrofurantoin: { dosage: '100 mg', frequency: '1-0-1', durationDays: 5, food: 'after food' },
  metronidazole: { dosage: '400 mg', frequency: '1-1-1', durationDays: 5, food: 'after food' },
  ciprofloxacin: { dosage: '500 mg', frequency: '1-0-1', durationDays: 5 },
  cotrimoxazole: { dosage: '960 mg', frequency: '1-0-1', durationDays: 5 },
  fluconazole: { dosage: '150 mg', frequency: 'once (single dose)', durationDays: 1 },
  albendazole: { dosage: '400 mg', frequency: 'once (single dose)', durationDays: 1 },
  amlodipine: { dosage: '5 mg', frequency: '1-0-0', durationDays: 30 },
  telmisartan: { dosage: '40 mg', frequency: '1-0-0', durationDays: 30 },
  losartan: { dosage: '50 mg', frequency: '1-0-0', durationDays: 30 },
  enalapril: { dosage: '5 mg', frequency: '1-0-0', durationDays: 30 },
  chlorthalidone: { dosage: '12.5 mg', frequency: '1-0-0', durationDays: 30 },
  hydrochlorothiazide: { dosage: '12.5 mg', frequency: '1-0-0', durationDays: 30 },
  atenolol: { dosage: '50 mg', frequency: '1-0-0', durationDays: 30 },
  metoprolol: { dosage: '25 mg', frequency: '1-0-0', durationDays: 30 },
  atorvastatin: { dosage: '10 mg', frequency: '0-0-1', durationDays: 30 },
  rosuvastatin: { dosage: '10 mg', frequency: '0-0-1', durationDays: 30 },
  aspirin: { dosage: '75 mg', frequency: '0-1-0', durationDays: 30, food: 'after food' },
  clopidogrel: { dosage: '75 mg', frequency: '1-0-0', durationDays: 30 },
  metformin: { dosage: '500 mg', frequency: '1-0-1', durationDays: 30, food: 'after food' },
  glimepiride: { dosage: '1 mg', frequency: '1-0-0', durationDays: 30, food: 'before food' },
  gliclazide: { dosage: '40 mg', frequency: '1-0-0', durationDays: 30, food: 'before food' },
  sitagliptin: { dosage: '100 mg', frequency: '1-0-0', durationDays: 30 },
  pantoprazole: { dosage: '40 mg', frequency: '1-0-0', durationDays: 14, food: 'before food' },
  omeprazole: { dosage: '20 mg', frequency: '1-0-0', durationDays: 14, food: 'before food' },
  rabeprazole: { dosage: '20 mg', frequency: '1-0-0', durationDays: 14, food: 'before food' },
  famotidine: { dosage: '20 mg', frequency: '1-0-1', durationDays: 14 },
  domperidone: { dosage: '10 mg', frequency: '1-1-1', durationDays: 3, food: 'before food' },
  ondansetron: { dosage: '4 mg', frequency: 'SOS (up to 3 times a day)', durationDays: 3 },
  dicyclomine: { dosage: '10 mg', frequency: 'SOS (up to 3 times a day)', durationDays: 3 },
  drotaverine: { dosage: '40 mg', frequency: 'SOS (up to 3 times a day)', durationDays: 3 },
  ors: { dosage: '1 sachet in 1 litre', frequency: 'after each loose stool', durationDays: 3 },
  zinc_sulfate: { dosage: '20 mg', frequency: '1-0-0', durationDays: 14 },
  cetirizine: { dosage: '10 mg', frequency: '0-0-1', durationDays: 7 },
  levocetirizine: { dosage: '5 mg', frequency: '0-0-1', durationDays: 7 },
  fexofenadine: { dosage: '120 mg', frequency: '1-0-0', durationDays: 7 },
  montelukast: { dosage: '10 mg', frequency: '0-0-1', durationDays: 14 },
  salbutamol: { dosage: '100 mcg/puff, 2 puffs', frequency: 'SOS', durationDays: 30 },
  levothyroxine: { dosage: '50 mcg', frequency: '1-0-0', durationDays: 42, food: 'empty stomach' },
  prednisolone: { dosage: '20 mg', frequency: '1-0-0', durationDays: 5, food: 'after food' },
  calcium_carbonate: { dosage: '500 mg', frequency: '0-1-0', durationDays: 30, food: 'after food' },
  cholecalciferol: { dosage: '60,000 IU', frequency: 'once a week', durationDays: 56 },
  ferrous_sulfate: { dosage: '1 tablet', frequency: '0-1-0', durationDays: 90, food: 'after food' },
  folic_acid: { dosage: '5 mg', frequency: '1-0-0', durationDays: 30 },
  cyanocobalamin: { dosage: '1500 mcg', frequency: '1-0-0', durationDays: 30 },
  amitriptyline: { dosage: '10 mg', frequency: '0-0-1', durationDays: 30 },
  sertraline: { dosage: '50 mg', frequency: '1-0-0', durationDays: 30 },
  escitalopram: { dosage: '10 mg', frequency: '1-0-0', durationDays: 30 },
  pregabalin: { dosage: '75 mg', frequency: '0-0-1', durationDays: 14 },
  tramadol: { dosage: '50 mg', frequency: 'SOS (up to 3 times a day)', durationDays: 3 },
  thiocolchicoside: { dosage: '4 mg', frequency: '1-0-1', durationDays: 5 },
  tamsulosin: { dosage: '0.4 mg', frequency: '0-0-1', durationDays: 30 },
  allopurinol: { dosage: '100 mg', frequency: '1-0-0', durationDays: 30, food: 'after food' },
  colchicine: { dosage: '0.5 mg', frequency: '1-0-1', durationDays: 5 }
};

export const COMMON_AYUSH_DOSES: Record<string, { dose: string; frequency: string; anupana: string; durationDays: number }> = {
  yogaraja_guggulu: { dose: '2 tablets (250 mg each)', frequency: '1-0-1 after food', anupana: 'Lukewarm water', durationDays: 30 },
  kaishore_guggulu: { dose: '2 tablets', frequency: '1-0-1 after food', anupana: 'Lukewarm water', durationDays: 30 },
  triphala_guggulu: { dose: '2 tablets', frequency: '1-0-1 after food', anupana: 'Lukewarm water', durationDays: 30 },
  avipattikar_churna: { dose: '3–6 g', frequency: '1-0-1 before food', anupana: 'Lukewarm water', durationDays: 15 },
  sitopaladi_churna: { dose: '3 g', frequency: '1-1-1', anupana: 'Honey', durationDays: 7 },
  talisadi_churna: { dose: '3 g', frequency: '1-1-1', anupana: 'Honey', durationDays: 7 },
  triphala_churna: { dose: '5 g', frequency: '0-0-1 at bedtime', anupana: 'Lukewarm water', durationDays: 15 },
  ashwagandha_churna: { dose: '3 g', frequency: '0-0-1 at bedtime', anupana: 'Warm milk', durationDays: 30 },
  shatavari_churna: { dose: '3 g', frequency: '1-0-1', anupana: 'Milk', durationDays: 30 },
  sudarshana_ghanavati: { dose: '2 tablets (500 mg)', frequency: '1-1-1 after food', anupana: 'Lukewarm water', durationDays: 5 },
  guduchi_ghanavati: { dose: '1 tablet (500 mg)', frequency: '1-0-1', anupana: 'Lukewarm water', durationDays: 15 },
  sanshamani_vati: { dose: '2 tablets', frequency: '1-0-1', anupana: 'Lukewarm water', durationDays: 15 },
  chandraprabha_vati: { dose: '2 tablets (250 mg)', frequency: '1-0-1 after food', anupana: 'Lukewarm water', durationDays: 30 },
  nishamalaki_vati: { dose: '2 tablets (500 mg)', frequency: '1-0-1 before food', anupana: 'Lukewarm water', durationDays: 30 },
  brahmi_vati: { dose: '1 tablet (250 mg)', frequency: '0-0-1', anupana: 'Warm milk', durationDays: 30 },
  rasnasaptaka_kwatha: { dose: '15 ml with equal water', frequency: '1-0-1 before food', anupana: 'Lukewarm water', durationDays: 30 },
  maharasnadi_kwatha: { dose: '15 ml with equal water', frequency: '1-0-1 before food', anupana: 'Lukewarm water', durationDays: 30 },
  dashamoolarishta: { dose: '15–20 ml with equal water', frequency: '1-0-1 after food', anupana: 'Water', durationDays: 30 },
  draksharishta: { dose: '15–20 ml with equal water', frequency: '1-0-1 after food', anupana: 'Water', durationDays: 30 },
  arjunarishta: { dose: '15–20 ml with equal water', frequency: '1-0-1 after food', anupana: 'Water', durationDays: 30 },
  vasavaleha: { dose: '10 g', frequency: '1-0-1', anupana: 'Lukewarm water', durationDays: 7 },
  chyawanprash: { dose: '10 g', frequency: '1-0-0', anupana: 'Warm milk', durationDays: 30 },
  kamdudha_ras: { dose: '250 mg', frequency: '1-0-1', anupana: 'Water', durationDays: 15 },
  praval_pishti: { dose: '125–250 mg', frequency: '1-0-1', anupana: 'Honey or water', durationDays: 15 },
  shallaki_f: { dose: '1 tablet (500 mg)', frequency: '1-0-1 after food', anupana: 'Lukewarm water', durationDays: 30 },
  haridra_khanda: { dose: '3 g', frequency: '1-0-1 after food', anupana: 'Warm milk', durationDays: 21 },
  yashtimadhu_churna: { dose: '3 g', frequency: '1-0-1', anupana: 'Milk', durationDays: 15 },
  hingvastak_churna: { dose: '2–3 g', frequency: 'with first morsel of lunch and dinner', anupana: 'Ghee', durationDays: 15 },
  mahanarayana_taila: { dose: 'For local application', frequency: 'Twice daily (external)', anupana: 'External use — warm massage', durationDays: 30 }
};
